# -*- coding: utf-8 -*-
"""2022_02_12

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13wWEueBgN4YUCEgJ_hxakk0qQGFLrYb9
"""

str1 = "A La So";
name = "Alan";
city = "Taipei";
title = "SD";

def fun_intro():
  intro = f"Hi, I'm {name}, a {title} from {city}.";
  print( intro )


def fun_str1():
  print( str1 )

def fun_1_10():
  for i in range(10):
    print( i )


fun_intro();

def fun_99_loop1():
  for a in range(1,10):
    for b in range(1,10):
      print( str( fun_padLeft( a, 2 ) ) + " x " + str( fun_padLeft( b, 2 ) ) + " = " + str( fun_padLeft( ( a * b ), 2 ) ) )

def fun_99_loop2():
  for a in range(1,10):
    for b in range(1,10):
      result = f"{a:02d} x {b:02d} = {( a * b ):02d}"
      # print( str(a) + " x " + str(b) + " = " + str( a * b ) )
      print( result );

def fun_99_loop3():
  for a in range(1,10):
    result = "";
    for b in range(1,10):
      result += f"{b:02d} x {a:02d} = {( a * b ):02d}   "
      # print( str(a) + " x " + str(b) + " = " + str( a * b ) )
      if b == a:break;
    print( result );


def fun_padLeft( inStr, inLen ):
  # print( type( inLen ) );
  # print( inLen );
  outStr = str( inStr );
  strLen = len( outStr );
  # print( isinstance( strLen, int ) );
  # print( isinstance( inLen, int ) );
  if( strLen < inLen ):
    outStr = "0" + outStr;
    outStr = fun_padLeft( outStr, inLen );
  return outStr;

def fun_demoPadeLeft( inNum, inLen ):
  ans = fun_padLeft( inNum, inLen );
  print( ans );

def fun_Input():
  inStr = input("Please input here:");
  print(f"This is {inStr}");

# fun_demoPadeLeft( 546, 26 );

# fun_99_loop1();

# fun_99_loop2();

fun_Input();
fun_99_loop3();

